export const CoffesList = [
  {
    id: 1,
    name: 'Expresso tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    price: 9.99,
    amount: 19,
    photo: './assets/coffes/expresso-tradicional.png',
    type: ['tradicional'],
  },
  {
    id: 2,
    name: 'Expresso americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    price: 9.99,
    amount: 22,
    photo: './assets/coffes/expresso-americano.png',
    type: ['tradicional'],
  },
  {
    id: 3,
    name: 'Expresso cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    price: 9.99,
    amount: 6,
    photo: './assets/coffes/expresso-cremoso.png',
    type: ['tradicional'],
  },
  {
    id: 4,
    name: 'Expresso gelado',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    price: 9.99,
    amount: 19,
    photo: './assets/coffes/expresso-gelado.png',
    type: ['tradicional', 'gelado'],
  },
  {
    id: 5,
    name: 'Café com Leite',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    price: 9.99,
    amount: 11,
    photo: './assets/coffes/café-com-leite.png',
    type: ['tradicional', 'com leite'],
  },
  {
    id: 6,
    name: 'Latte',
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    price: 9.99,
    amount: 4,
    photo: './assets/coffes/latte.png',
    type: ['tradicional', 'com leite'],
  },
  {
    id: 7,
    name: 'Capuccino',
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    price: 9.99,
    amount: 19,
    photo: './assets/coffes/capuccino.png',
    type: ['tradicional', 'com leite'],
  },
  {
    id: 8,
    name: 'Macchiato',
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    price: 9.99,
    amount: 19,
    photo: './assets/coffes/macchiato.png',
    type: ['tradicional', 'com leite'],
  },
  {
    id: 9,
    name: 'Mocaccino',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    price: 9.99,
    amount: 19,
    photo: './assets/coffes/mocaccino.png',
    type: ['tradicional'],
  },
  {
    id: 10,
    name: 'Chocolate Quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    price: 9.99,
    amount: 19,
    photo: './assets/coffes/chocolate-quente.png',
    type: ['especial', 'com leite'],
  },
  {
    id: 11,
    name: 'Cubano',
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    price: 9.99,
    amount: 19,
    photo: './assets/coffes/cubano.png',
    type: ['especial', 'alcoólico', 'gelado'],
  },
  {
    id: 12,
    name: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de coco',
    price: 9.99,
    amount: 19,
    photo: './assets/coffes/havaiano.png',
    type: ['especial'],
  },
];
